on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: tyrantdavis/barsoom@0.0.2
        with:
          name: "Hore-em-Ma-Khuti"
      # Use the output from the `hello` step --
      - name: Get the output salutation
        run: echo "The time was ${{ steps.hello.outputs.salutation }}"
