on:
  push:
    branches:
      - main
      - dev
  pull_requests:
    branches:
      - main

jobs: 
  hello_world:
    runs_on: ubuntu-latest
    steps: 
      - name: "Echo Basic Information"
        run: |
          echo "REF: $GITHUB_REF"
          echo "Job ID: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"    
          echo "Actor: $GITHUB_ACTOR"