name: Workflow Commands

on:
  push:
    branches:
      - main
jobs:
  workflow-commands-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Group Logging"
        run: |
          echo "::group::Workflow Commands Group"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"
      - name: "Step 1 - Capture ENV value"
        run: |
          echo "ENV_VALUE=Greetings" >> GITHUB_ENV
      - name: "Step 2 - Use ENV value"
        run: |
          echo $ENV_VALUE
